project_id = "hwwwjfzmpgerrkigpgab"

[functions.generate-letter]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.manage-users]
verify_jwt = false

[functions.process-notifications]
verify_jwt = true

[functions.notify-gg-open-folio]
verify_jwt = true

[functions.notify-gg-to-invoice]
verify_jwt = true